name: Daily GitHub Issue Summary

on:
  schedule:
   - cron: '15 15 * * *'
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install requests
        run: pip install requests

      - name: Run summary bot
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python3 summary_bot.py
